# Generated by Django 3.1.6 on 2021-02-10 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('table_no', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Waiter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('waiter', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('arrival', models.DateTimeField(auto_now_add=True)),
                ('exit', models.DateTimeField(blank=True, null=True)),
                ('total_ammount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.table')),
                ('waiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.waiter')),
            ],
        ),
    ]
