# Generated by Django 3.1.6 on 2021-02-11 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_auto_20210210_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='table',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='tables.table'),
        ),
        migrations.AlterField(
            model_name='service',
            name='waiter',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='tables.waiter'),
        ),
    ]
