# Generated by Django 3.1.6 on 2021-02-11 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0003_auto_20210211_1529'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='total_ammount',
            new_name='tip',
        ),
    ]
